### PR TITLE
Make zigglgen compatible with Zig master

### PR DESCRIPTION
**Pull request by terraquad**
> [!CAUTION]
> This will remove mach and stable version support altogether.

This PR will make zigglgen compatible with Zig's master branch. This will also break compatibility with the versions mentioned above because `std.builtin.Type` and `std.Build` have changed quite a lot.

Depends on #11 and closes #12

### CODE REVIEW

**Comment by terraquad** [comment]
@castholm I've just read your [comment](https://github.com/castholm/zigglgen/pull/11#issuecomment-2383370480) on #11 so... should I close this? Or keep it for reference?

**Comment by castholm** [comment]
You can close it or leave it open, but either way I'll need to make all the necessary project structure changes and compiler version updates on my own as part of a larger single changeset that supersedes this PR.

I appreciate the eagerness to help and I'm sorry if I've made you feel like you wasted your time. If you had reached out before you put in the work we could have spared you the trouble. If I end up using anything from your PRs I'll make sure you credit you as a co-author.

**Comment by castholm** [comment]
Incorporated into 33d283618af7e904be1d70a32a0fdb0921f70130

I managed to get it working on both 0.12.1, 0.13.0 and master. It's not very nice to look at but it does the job.

**Comment by castholm** [comment]
(I'm holding out on making a tagged release until I've moved the example and updated some documentation, but I need to wait for mach-glfw to get up to date first. But `zig fetch`ing the repository itself should work now across all supported versions.)

**Pull request closed without merging**
